const App=(()=>{let currentView='today';function nav(view){currentView=view;document.querySelectorAll('.nav-btn').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);});document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));const el=document.getElementById(`view-${view}`);if(el)el.classList.add('active');refresh();}
function refresh(){const t=document.getElementById('todayDate');if(t)t.textContent=new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});const tt=document.getElementById('todayTitle');if(tt)tt.textContent='Today';switch(currentView){case'today':Sched.render('schedGrid','schedLabel',Sched.getOffset());break;case'week':Week.render();break;case'month':Month.render();break;case'stats':Stats.render();break;}}
function setupKeyboard(){document.addEventListener('keydown',e=>{const meta=e.metaKey||e.ctrlKey;const tag=(e.target&&e.target.tagName)||'';const inField=['INPUT','TEXTAREA','SELECT'].includes(tag)||e.target?.isContentEditable;if(meta&&e.key.toLowerCase()==='k'){e.preventDefault();if(document.getElementById('cmdkOverlay').classList.contains('open'))CmdK.close();else CmdK.open();return;}if(meta&&e.key===','){e.preventDefault();Settings.open();return;}if(meta&&e.key==='/'){e.preventDefault();if(Settings.get('sAIEnabled',true))AI.toggle();return;}if(meta&&e.key.toLowerCase()==='z'&&!e.shiftKey){e.preventDefault();Store.undo();return;}if(meta&&(e.key.toLowerCase()==='y'||(e.key.toLowerCase()==='z'&&e.shiftKey))){e.preventDefault();Store.redo();return;}if(inField)return;if(e.key==='Escape'){document.querySelectorAll('.modal-overlay.open').forEach(o=>o.classList.remove('open'));const p=document.getElementById('aiPanel');if(p&&p.classList.contains('open'))p.classList.remove('open');return;}if(e.key==='t'||e.key==='T'){nav('today');return;}if(e.key==='w'||e.key==='W'){nav('week');return;}if(e.key==='m'||e.key==='M'){nav('month');return;}if(e.key==='n'||e.key==='N'){BlockModal.open(Store.todayStr(),12,0);return;}if(e.key==='q'||e.key==='Q'){QuickAdd.open();return;}});document.addEventListener('keydown',e=>{const tag=(e.target&&e.target.tagName)||'';const inField=['INPUT','TEXTAREA','SELECT'].includes(tag)||e.target?.isContentEditable;if(inField)return;if(!document.getElementById('view-today').classList.contains('active'))return;if(e.key==='ArrowLeft'){Sched.shift(-1);e.preventDefault();}if(e.key==='ArrowRight'){Sched.shift(1);e.preventDefault();}});}
async function init(){Settings.init();await Store.pull();if(typeof Affirmation!=='undefined')Affirmation.init();AI.init();Notify.init();if(typeof Classes!=='undefined')Classes.refreshAllSelects();setupKeyboard();setInterval(()=>{if(currentView==='today')Sched.renderBoth();},60000);let _lastFocusPull=0;window.addEventListener('focus',async()=>{if(Date.now()-_lastFocusPull<3000)return;_lastFocusPull=Date.now();const changed=await Store.pull();if(changed)refresh();});document.addEventListener('visibilitychange',async()=>{if(document.visibilityState!=='visible')return;if(Date.now()-_lastFocusPull<3000)return;_lastFocusPull=Date.now();const changed=await Store.pull();if(changed)refresh();});setInterval(async()=>{if(document.visibilityState!=='visible')return;const changed=await Store.pull();if(changed)refresh();},60000);
// Auto-sync calendar subscriptions on boot (delayed so UI can render first)
if(typeof Cal!=='undefined'){setTimeout(()=>Cal.syncAll({silent:true}),3000);}
nav('today');}
return{nav,refresh,init};})();
document.addEventListener('DOMContentLoaded',App.init);
